server:
  port: 9000

# 是否是demo环境, 如果为demo环境, 则不允许进行操作
# demo: true

spring:
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://110.40.143.67:3308/grape?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: asdewq/.,321
    # druid 数据库连接池配置
    druid:
      initial-size: 5
      max-active: 100
      min-idle: 1
      max-wait: 60000

# mybatis-plus 配置
mybatis-plus:
  # 别名定义包
  typeAliasesPackage: cn.silently9527.coupons.repository.databases.entity
  mapperLocations: classpath:/cn/silently9527/coupons/repository/databases/mapper/xml/*Mapper.xml
  configuration:
    mapUnderscoreToCamelCase: true

# 日志文件的配置
logging:
  config: file:logging-config.xml

# 系统核心配置
system:
  # 超级管理角色编号
  superRoleCode: super_admin
  # 超级管理员id
  superAdminId: 1
  # 是否启用swagger
  swaggerEnable: false
  # jwt 签名key
  jwtSigningKey: defaultSigningKey
  # 不需要授权的接口地址匹配
  noAuthPathPatterns:

# 插件的配置
plugin:
  # 插件运行模式. dev: 开发环境, prod: 生产环境
  runMode: prod
  # 是否启用插件
  enable: true
  # 插件存放的目录
  pluginPath: plugins
  # 生产环境下, 插件文件的路径. 只在生产环境下生效
  pluginConfigFilePath: plugin-configs
  # 插件rest接口前缀
  pluginRestPathPrefix: /api/plugins/
  # 在卸载插件后, 备份插件的目录
  backupPluginPath: backupPlugin
  # 上传的插件所存储的临时目录
  uploadTempPath: temp
  # 禁用的插件id, 禁用后系统不会启动该插件. 为Set集合. 配置案例如下:
  # disablePluginIds:
  #   - disable-id1
  #   - disable-id2
  disablePluginIds:

# web界面配置
web:
  webLocation: classpath:/coupons-console/
  # web 界面的配置
  config:
    # 服务的接口url地址, 默认为空, 表示使用浏览器访问的地址
    serverUrl:
    # 前端插件请求插件接口的api前缀
    pluginApiPrefix: ${plugin.pluginRestPathPrefix}
    # 密码传输是否使用加密
    passwordEncryption: true
    # OAuth2 客户端id
    clientId: admin_client
    # OAuth2 秘钥
    clientSecret: f640e16a951b4109a88cf0fcd4d66a63